# Docker Compose configuration for Basic Memory
# See docs/Docker.md for detailed setup instructions

version: '3.8'

services:
  basic-memory:
    build: .
    container_name: basic-memory-server
    
    # Volume mounts for knowledge directories and persistent data
    volumes:
      # REQUIRED: Mount your Obsidian vault or knowledge directory
      # Change './obsidian-vault' to your actual directory path
      # Example: - /Users/yourname/Documents/ObsidianVault:/data/knowledge:rw
      - ./obsidian-vault:/data/knowledge:rw
      
      # RECOMMENDED: Persistent storage for configuration and database
      - basic-memory-config:/root/.basic-memory:rw
      
      # OPTIONAL: Mount additional knowledge directories for multiple projects
      # - ./work-notes:/data/projects/work:rw
      # - ./personal-notes:/data/projects/personal:rw
    
    environment:
      # Project configuration - maps project names to container paths
      - BASIC_MEMORY_PROJECTS={"main": "/data/knowledge"}
      - BASIC_MEMORY_DEFAULT_PROJECT=main
      
      # Enable real-time file synchronization (recommended for Docker)
      - BASIC_MEMORY_SYNC_CHANGES=true
      
      # Logging configuration
      - BASIC_MEMORY_LOG_LEVEL=INFO
      
      # Sync delay in milliseconds (adjust for performance vs responsiveness)
      - BASIC_MEMORY_SYNC_DELAY=1000
    
    # Port exposure for HTTP transport (only needed if not using STDIO)
    ports:
      - "8000:8000"
    
    # Command options:
    
    # Option 1: STDIO transport (default, recommended for MCP clients)
    command: ["basic-memory", "mcp"]
    
    # Option 2: HTTP Server-Sent Events transport (uncomment to use)
    # command: ["basic-memory", "mcp", "--transport", "sse", "--host", "0.0.0.0", "--port", "8000"]
    
    # Option 3: HTTP streamable transport (uncomment to use)
    # command: ["basic-memory", "mcp", "--transport", "streamable-http", "--host", "0.0.0.0", "--port", "8000"]
    
    # Container management
    restart: unless-stopped
    
    # Health monitoring
    healthcheck:
      test: ["CMD", "basic-memory", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Optional: Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 256M
    #       cpus: '0.25'

volumes:
  # Named volume for persistent configuration and database
  # This ensures your configuration and knowledge graph persist across container restarts
  basic-memory-config:
    driver: local

# Network configuration (optional)
# networks:
#   basic-memory-net:
#     driver: bridge